# Generated by Django 6.1 on 2026-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_user_id', models.CharField(max_length=100)),
                ('source_playlist_a_name', models.CharField(max_length=200)),
                ('source_playlist_b_name', models.CharField(max_length=200)),
                ('new_playlist_id', models.CharField(max_length=100)),
                ('new_playlist_name', models.CharField(max_length=200)),
                ('track_count', models.PositiveIntegerField()),
                ('duplicates_removed', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
